#!/usr/bin/env python3
"""
Forest Plot Generator
======================

Generates SAS code for Figure 14.2.x: Forest Plot for Subgroup Analysis.
Creates publication-quality forest plots showing treatment effects by subgroup.

Output: f_forest.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class ForestPlotGenerator(SASCodeGenerator):
    """Generate subgroup analysis forest plot."""

    @property
    def program_name(self) -> str:
        return "f_forest.sas"

    @property
    def program_purpose(self) -> str:
        return "Figure 14.2.1: Forest Plot - Subgroup Analysis"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete forest plot program."""

        # Determine endpoint type for appropriate effect measure
        primary_endpoint = self._get_fact(facts, 'primary_endpoint', {})
        if isinstance(primary_endpoint, dict):
            endpoint_type = primary_endpoint.get('type', 'binary')
            endpoint_name = primary_endpoint.get('name', 'Primary Endpoint')
        else:
            endpoint_type = 'binary'
            endpoint_name = str(primary_endpoint) if primary_endpoint else 'Primary Endpoint'

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts, endpoint_type, endpoint_name)
        code += self._generate_subgroup_definitions(facts)
        code += self._generate_analysis_section(endpoint_type)
        code += self._generate_forest_plot_macro()
        code += self._generate_plot_output(facts, endpoint_type, endpoint_name)
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL', 'ADEFF'],
            output_datasets=['f_forest.png', 'f_forest.rtf'],
            validation_notes=[
                "Verify subgroup definitions match SAP",
                "Check consistency of effect measure (OR/RR/HR/difference)",
                "Confirm confidence interval level matches protocol",
                "Validate treatment comparison direction",
                "Review heterogeneity test if included"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

/* Forest Plot Requirements:
/*   - Subgroup analysis of primary endpoint
/*   - Treatment effect with 95% CI by subgroup
/*   - Interaction p-values (optional)
/*   - Overall treatment effect for reference
*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any], endpoint_type: str,
                                   endpoint_name: str) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        # Determine effect measure based on endpoint type
        if endpoint_type == 'binary':
            effect_measure = 'Odds Ratio'
            effect_abbrev = 'OR'
        elif endpoint_type == 'time_to_event':
            effect_measure = 'Hazard Ratio'
            effect_abbrev = 'HR'
        else:
            effect_measure = 'Difference'
            effect_abbrev = 'DIFF'

        treatments = self._get_fact(facts, 'treatments', [])
        if len(treatments) >= 2:
            active_trt = treatments[0].get('name', 'Active')
            control_trt = treatments[-1].get('name', 'Placebo')
        else:
            active_trt = 'Active'
            control_trt = 'Placebo'

        return f"""/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

%let STUDYID = {study_id};
%let FIGURE_NUM = 14.2.1;
%let FIGURE_TITLE = Forest Plot - Subgroup Analysis of Primary Endpoint;
%let outpath = /output/&STUDYID.;

/* Endpoint information */
%let ENDPOINT_NAME = {endpoint_name};
%let ENDPOINT_TYPE = {endpoint_type};
%let EFFECT_MEASURE = {effect_measure};
%let EFFECT_ABBREV = {effect_abbrev};

/* Treatment comparison */
%let ACTIVE_TRT = {active_trt};
%let CONTROL_TRT = {control_trt};
%let COMPARISON = &ACTIVE_TRT vs &CONTROL_TRT;

/* Confidence level */
%let CI_LEVEL = 0.95;
%let ALPHA = 0.05;

/* Plot parameters */
%let PLOT_WIDTH = 10in;
%let PLOT_HEIGHT = 8in;
%let MARKER_SIZE = 10;

"""

    def _generate_subgroup_definitions(self, facts: Dict[str, Any]) -> str:
        """Generate subgroup variable definitions."""
        stratification = self._get_fact(facts, 'stratification_factors', [])

        code = """/*============================================================================*/
/* Subgroup Definitions                                                       */
/*============================================================================*/

/* Define subgroups for analysis - modify as needed per protocol */

data work.subgroup_defs;
    length SUBGROUP $50 SUBGRP_VAR $32 SUBGRP_ORDER 8 CATEGORY $50 CAT_ORDER 8;
    infile datalines dlm='|' truncover;
    input SUBGROUP $ SUBGRP_VAR $ SUBGRP_ORDER CATEGORY $ CAT_ORDER;
    datalines;
Overall|OVERALL|0|All Patients|1
"""
        # Add standard subgroups
        standard_subgroups = [
            ("Age Group|AGEGR1|1|<65 years|1", "Age Group|AGEGR1|1|>=65 years|2"),
            ("Sex|SEX|2|Male|1", "Sex|SEX|2|Female|2"),
            ("Race|RACE|3|White|1", "Race|RACE|3|Non-White|2"),
            ("Region|REGION|4|North America|1", "Region|REGION|4|Europe|2", "Region|REGION|4|Other|3"),
            ("Baseline Disease Severity|BSEVGR|5|Mild/Moderate|1", "Baseline Disease Severity|BSEVGR|5|Severe|2"),
        ]

        for subgroup_set in standard_subgroups:
            for item in subgroup_set:
                code += item + "\n"

        # Add protocol-specific stratification factors
        for i, factor in enumerate(stratification, 6):
            if isinstance(factor, str):
                var_name = factor.replace(' ', '').replace('/', '').replace('(', '').replace(')', '')[:8].upper()
                code += f"{factor}|{var_name}|{i}|Yes|1\n"
                code += f"{factor}|{var_name}|{i}|No|2\n"

        code += """;\nrun;

/* Create overall analysis flag */
data work.analysis_data;
    set adam.adsl (keep=USUBJID ITTFL TRT01P TRT01PN AGE AGEGR1 SEX RACE COUNTRY);
    where ITTFL = 'Y';

    /* Overall flag for total population */
    OVERALL = 'Y';

    /* Age group if not already derived */
    if missing(AGEGR1) then do;
        if AGE < 65 then AGEGR1 = '<65 years';
        else AGEGR1 = '>=65 years';
    end;

    /* Race grouping */
    length RACEGR $20;
    if upcase(RACE) = 'WHITE' then RACEGR = 'White';
    else RACEGR = 'Non-White';

    /* Region based on country */
    length REGION $20;
    if COUNTRY in ('USA', 'CAN') then REGION = 'North America';
    else if COUNTRY in ('DEU', 'FRA', 'GBR', 'ESP', 'ITA', 'POL') then REGION = 'Europe';
    else REGION = 'Other';
run;

/* Merge with efficacy data */
proc sort data=work.analysis_data; by USUBJID; run;
proc sort data=adam.adeff out=work.eff (where=(ANL01FL='Y')); by USUBJID; run;

data work.forest_data;
    merge work.analysis_data (in=a)
          work.eff (in=b keep=USUBJID PARAMCD AVAL AVALC);
    by USUBJID;
    if a;

    /* Create binary response for primary endpoint */
    if AVALC = 'Y' then RESP = 1;
    else RESP = 0;
run;

"""
        return code

    def _generate_analysis_section(self, endpoint_type: str) -> str:
        """Generate statistical analysis section."""
        return """/*============================================================================*/
/* Subgroup Analysis                                                          */
/*============================================================================*/

%macro analyze_subgroup(subgrp_var=, subgrp_val=, subgrp_label=, order=);

    /* Subset to subgroup */
    data work._subgrp;
        set work.forest_data;
        %if &subgrp_var ne OVERALL %then %do;
            where &subgrp_var = "&subgrp_val";
        %end;
    run;

    /* Count subjects */
    proc sql noprint;
        select count(distinct USUBJID) into :N_SUBGRP trimmed
        from work._subgrp;

        select count(distinct USUBJID) into :N_TRT trimmed
        from work._subgrp where TRT01PN = 1;

        select count(distinct USUBJID) into :N_CTL trimmed
        from work._subgrp where TRT01PN = 2;
    quit;

    %if &endpoint_type = binary %then %do;
        /* Logistic regression for odds ratio */
        proc logistic data=work._subgrp descending;
            class TRT01PN (ref='2');
            model RESP = TRT01PN;
            ods output OddsRatios=work._or ParameterEstimates=work._pe;
        run;

        data work._result;
            set work._or;
            where Effect = 'TRT01PN';
            SUBGROUP = "&subgrp_label";
            SUBGRP_ORDER = &order;
            N_TOTAL = &N_SUBGRP;
            N_TRT = &N_TRT;
            N_CTL = &N_CTL;
            EFFECT = OddsRatioEst;
            EFFECT_LCL = LowerCL;
            EFFECT_UCL = UpperCL;

            /* Calculate log scale for plotting */
            LOG_EFFECT = log(EFFECT);
            LOG_LCL = log(EFFECT_LCL);
            LOG_UCL = log(EFFECT_UCL);
        run;
    %end;
    %else %if &endpoint_type = time_to_event %then %do;
        /* Cox regression for hazard ratio */
        proc phreg data=work._subgrp;
            class TRT01PN (ref='2');
            model AVAL*CNSR(1) = TRT01PN;
            hazardratio TRT01PN;
            ods output HazardRatios=work._hr;
        run;

        data work._result;
            set work._hr;
            SUBGROUP = "&subgrp_label";
            SUBGRP_ORDER = &order;
            N_TOTAL = &N_SUBGRP;
            N_TRT = &N_TRT;
            N_CTL = &N_CTL;
            EFFECT = HazardRatio;
            EFFECT_LCL = HRLowerCL;
            EFFECT_UCL = HRUpperCL;
            LOG_EFFECT = log(EFFECT);
            LOG_LCL = log(EFFECT_LCL);
            LOG_UCL = log(EFFECT_UCL);
        run;
    %end;
    %else %do;
        /* ANCOVA for continuous - treatment difference */
        proc mixed data=work._subgrp;
            class TRT01PN;
            model AVAL = TRT01PN / solution;
            lsmeans TRT01PN / diff cl;
            ods output Diffs=work._diff;
        run;

        data work._result;
            set work._diff;
            where TRT01PN = 1 and _TRT01PN = 2;
            SUBGROUP = "&subgrp_label";
            SUBGRP_ORDER = &order;
            N_TOTAL = &N_SUBGRP;
            N_TRT = &N_TRT;
            N_CTL = &N_CTL;
            EFFECT = Estimate;
            EFFECT_LCL = Lower;
            EFFECT_UCL = Upper;
            /* No log transform for difference */
            LOG_EFFECT = EFFECT;
            LOG_LCL = EFFECT_LCL;
            LOG_UCL = EFFECT_UCL;
        run;
    %end;

    /* Append to results */
    proc append base=work.all_results data=work._result force; run;

    /* Clean up */
    proc datasets library=work nolist;
        delete _subgrp _or _pe _hr _diff _result;
    quit;

%mend analyze_subgroup;

/* Initialize results dataset */
data work.all_results;
    length SUBGROUP $100;
    stop;
run;

/* Run analysis for each subgroup */
%macro run_all_subgroups;

    /* Overall */
    %analyze_subgroup(subgrp_var=OVERALL, subgrp_val=Y, subgrp_label=Overall, order=0);

    /* Age */
    %analyze_subgroup(subgrp_var=AGEGR1, subgrp_val=<65 years, subgrp_label=Age <65 years, order=1.1);
    %analyze_subgroup(subgrp_var=AGEGR1, subgrp_val=>=65 years, subgrp_label=Age >=65 years, order=1.2);

    /* Sex */
    %analyze_subgroup(subgrp_var=SEX, subgrp_val=M, subgrp_label=Male, order=2.1);
    %analyze_subgroup(subgrp_var=SEX, subgrp_val=F, subgrp_label=Female, order=2.2);

    /* Race */
    %analyze_subgroup(subgrp_var=RACEGR, subgrp_val=White, subgrp_label=White, order=3.1);
    %analyze_subgroup(subgrp_var=RACEGR, subgrp_val=Non-White, subgrp_label=Non-White, order=3.2);

    /* Region */
    %analyze_subgroup(subgrp_var=REGION, subgrp_val=North America, subgrp_label=North America, order=4.1);
    %analyze_subgroup(subgrp_var=REGION, subgrp_val=Europe, subgrp_label=Europe, order=4.2);
    %analyze_subgroup(subgrp_var=REGION, subgrp_val=Other, subgrp_label=Other Region, order=4.3);

%mend run_all_subgroups;

%run_all_subgroups;

/* Sort results */
proc sort data=work.all_results;
    by SUBGRP_ORDER;
run;

"""

    def _generate_forest_plot_macro(self) -> str:
        """Generate the forest plot rendering macro."""
        return """/*============================================================================*/
/* Forest Plot Macro                                                          */
/*============================================================================*/

%macro create_forest_plot(data=, effect_var=, lcl_var=, ucl_var=,
                          ref_line=1, log_scale=Y, outfile=);

    /* Prepare annotation dataset */
    data work._anno;
        set &data;

        /* Row position (reverse for top-to-bottom display) */
        ROW = _N_;

        /* Format effect estimate and CI for display */
        length EFFECT_DISP $50;
        EFFECT_DISP = strip(put(&effect_var, 5.2)) ||
                      ' (' || strip(put(&lcl_var, 5.2)) || ', ' ||
                      strip(put(&ucl_var, 5.2)) || ')';

        /* Format N */
        length N_DISP $20;
        N_DISP = strip(put(N_TOTAL, comma8.));
    run;

    /* Create the plot */
    ods graphics on / reset=all width=&PLOT_WIDTH height=&PLOT_HEIGHT imagename="&outfile";

    proc sgplot data=work._anno noautolegend;

        /* Reference line at null effect */
        refline &ref_line / axis=x lineattrs=(color=gray pattern=dash);

        /* Confidence intervals as lines */
        %if &log_scale = Y %then %do;
            highlow y=ROW low=LOG_LCL high=LOG_UCL /
                lineattrs=(color=navy thickness=2);

            /* Point estimates as markers */
            scatter y=ROW x=LOG_EFFECT /
                markerattrs=(symbol=squarefilled color=navy size=&MARKER_SIZE);
        %end;
        %else %do;
            highlow y=ROW low=&lcl_var high=&ucl_var /
                lineattrs=(color=navy thickness=2);

            scatter y=ROW x=&effect_var /
                markerattrs=(symbol=squarefilled color=navy size=&MARKER_SIZE);
        %end;

        /* Y-axis labels with subgroup names */
        yaxis type=discrete discreteorder=data reverse
              label=' '
              values=(1 to %sysfunc(countw(%sysfunc(compress(&data)))));

        /* X-axis */
        %if &log_scale = Y %then %do;
            xaxis label="&EFFECT_MEASURE (95% CI)"
                  values=(-2 to 2 by 0.5)
                  valuesdisplay=('0.13' '0.25' '0.5' '1' '2' '4' '8');
        %end;
        %else %do;
            xaxis label="&EFFECT_MEASURE (95% CI)";
        %end;

    run;

    ods graphics off;

%mend create_forest_plot;

"""

    def _generate_plot_output(self, facts: Dict[str, Any], endpoint_type: str,
                               endpoint_name: str) -> str:
        """Generate plot output section."""
        ref_line = "0" if endpoint_type == "continuous" else "1"
        log_scale = "N" if endpoint_type == "continuous" else "Y"

        return f"""/*============================================================================*/
/* Generate Forest Plot Output                                                */
/*============================================================================*/

/* Prepare final plot data */
data work.plot_data;
    set work.all_results;

    /* Create display order (Overall first, then by subgroup) */
    if SUBGRP_ORDER = 0 then PLOT_ORDER = 0;
    else PLOT_ORDER = SUBGRP_ORDER;

    /* Create row labels with N */
    length ROW_LABEL $100;
    ROW_LABEL = strip(SUBGROUP) || ' (N=' || strip(put(N_TOTAL, comma8.)) || ')';

    /* Format statistics for display */
    length STAT_DISP $50;
    STAT_DISP = strip(put(EFFECT, 5.2)) ||
                ' (' || strip(put(EFFECT_LCL, 5.2)) || ', ' ||
                strip(put(EFFECT_UCL, 5.2)) || ')';
run;

proc sort data=work.plot_data;
    by PLOT_ORDER;
run;

/* Create forest plot using SGPLOT */
options orientation=landscape nodate nonumber;
ods graphics on / reset=all width=10in height=8in imagefmt=png imagename="f_forest";

ods rtf file="&outpath./f_forest.rtf" style=journal;

title1 "Figure &FIGURE_NUM";
title2 "&FIGURE_TITLE";
title3 "&ENDPOINT_NAME - &COMPARISON";
title4 "ITT Population";

footnote1 "Effect measure: &EFFECT_MEASURE with 95% confidence interval";
footnote2 "Vertical dashed line represents null effect ({'1' if endpoint_type != 'continuous' else '0'})";
footnote3 "Favors &ACTIVE_TRT <-- | --> Favors &CONTROL_TRT";
footnote4 "Program: {self.program_name}  Output: f_forest.rtf";

proc sgplot data=work.plot_data noautolegend;

    /* Reference line at null effect */
    refline {ref_line} / axis=x lineattrs=(color=gray pattern=dash thickness=1);

    /* Confidence intervals */
    %if &ENDPOINT_TYPE = binary or &ENDPOINT_TYPE = time_to_event %then %do;
        highlow y=ROW_LABEL low=LOG_LCL high=LOG_UCL /
            lineattrs=(color=navy thickness=2)
            type=line;

        scatter y=ROW_LABEL x=LOG_EFFECT /
            markerattrs=(symbol=diamondfilled color=navy size=12);

        xaxis label="&EFFECT_ABBREV (95% CI) - Log Scale"
              values=(-1.5 to 1.5 by 0.5)
              valuesdisplay=('0.22' '0.37' '0.61' '1.0' '1.65' '2.72' '4.48');
    %end;
    %else %do;
        highlow y=ROW_LABEL low=EFFECT_LCL high=EFFECT_UCL /
            lineattrs=(color=navy thickness=2)
            type=line;

        scatter y=ROW_LABEL x=EFFECT /
            markerattrs=(symbol=diamondfilled color=navy size=12);

        xaxis label="Treatment Difference (95% CI)";
    %end;

    yaxis type=discrete discreteorder=data reverse
          label=' '
          fitpolicy=none
          offsetmin=0.05 offsetmax=0.05;

run;

ods rtf close;
ods graphics off;

title; footnote;

/* Also save as PNG */
ods graphics on / reset=all width=10in height=8in imagefmt=png;
ods listing gpath="&outpath.";

proc sgplot data=work.plot_data noautolegend;
    refline {ref_line} / axis=x lineattrs=(color=gray pattern=dash thickness=1);

    %if &ENDPOINT_TYPE = binary or &ENDPOINT_TYPE = time_to_event %then %do;
        highlow y=ROW_LABEL low=LOG_LCL high=LOG_UCL /
            lineattrs=(color=navy thickness=2) type=line;
        scatter y=ROW_LABEL x=LOG_EFFECT /
            markerattrs=(symbol=diamondfilled color=navy size=12);
        xaxis label="&EFFECT_ABBREV (95% CI)" values=(-1.5 to 1.5 by 0.5);
    %end;
    %else %do;
        highlow y=ROW_LABEL low=EFFECT_LCL high=EFFECT_UCL /
            lineattrs=(color=navy thickness=2) type=line;
        scatter y=ROW_LABEL x=EFFECT /
            markerattrs=(symbol=diamondfilled color=navy size=12);
        xaxis label="Treatment Difference (95% CI)";
    %end;

    yaxis type=discrete discreteorder=data reverse label=' ';
run;

ods listing close;
ods graphics off;

/* Save analysis results */
data adam.f_forest_results;
    set work.plot_data;
run;

%put NOTE: Forest plot completed successfully;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program f_forest.sas completed successfully;
%put NOTE: ================================================================;
"""
