#!/usr/bin/env python3
"""
Kaplan-Meier Plot Generator
============================

Generates SAS code for Figure 14.2.x: Kaplan-Meier Survival Curves.
Creates publication-quality survival plots for time-to-event endpoints.

Output: f_km.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class KaplanMeierPlotGenerator(SASCodeGenerator):
    """Generate Kaplan-Meier survival plot."""

    @property
    def program_name(self) -> str:
        return "f_km.sas"

    @property
    def program_purpose(self) -> str:
        return "Figure 14.2.2: Kaplan-Meier Survival Curves"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete Kaplan-Meier plot program."""

        # Determine endpoint
        primary_endpoint = self._get_fact(facts, 'primary_endpoint', {})
        if isinstance(primary_endpoint, dict):
            endpoint_name = primary_endpoint.get('name', 'Time to Event')
            endpoint_type = primary_endpoint.get('type', 'time_to_event')
        else:
            endpoint_name = str(primary_endpoint) if primary_endpoint else 'Time to Event'
            endpoint_type = 'time_to_event'

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts, endpoint_name)
        code += self._generate_data_prep()
        code += self._generate_survival_analysis()
        code += self._generate_km_plot_macro()
        code += self._generate_plot_output(facts, endpoint_name)
        code += self._generate_median_survival_table()
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL', 'ADTTE'],
            output_datasets=['f_km.png', 'f_km.rtf', 't_survival.rtf'],
            validation_notes=[
                "Verify event definition matches protocol",
                "Check censoring is applied correctly",
                "Confirm at-risk table counts are accurate",
                "Validate median survival calculations",
                "Review log-rank p-value computation"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

/* Kaplan-Meier Plot Requirements:
/*   - Survival probability curves by treatment group
/*   - Number at risk table below plot
/*   - Median survival with 95% CI
/*   - Log-rank test p-value
/*   - Hazard ratio with 95% CI (optional)
*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any], endpoint_name: str) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        treatments = self._get_fact(facts, 'treatments', [])
        if not treatments:
            arm_names = self._get_fact(facts, 'arm_names', ['Treatment', 'Placebo'])
            treatments = [{'name': name} for name in arm_names]

        code = f"""/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

%let STUDYID = {study_id};
%let FIGURE_NUM = 14.2.2;
%let FIGURE_TITLE = Kaplan-Meier Survival Curves;
%let ENDPOINT = {endpoint_name};
%let outpath = /output/&STUDYID.;

/* Time axis settings */
%let TIME_UNIT = Months;    /* Weeks, Months, or Years */
%let TIME_MAX = 24;         /* Maximum time for x-axis */
%let TIME_BY = 3;           /* Tick interval */

/* Plot dimensions */
%let PLOT_WIDTH = 10in;
%let PLOT_HEIGHT = 7in;

/* Number of treatments */
%let N_TRTS = {len(treatments)};

/* Treatment labels and colors */
"""
        # Define colors for each treatment
        colors = ['blue', 'red', 'green', 'orange', 'purple', 'brown']
        for i, trt in enumerate(treatments):
            name = trt.get('name', f'Treatment {i+1}')
            color = colors[i % len(colors)]
            code += f"%let TRT{i+1} = {name};\n"
            code += f"%let TRT{i+1}_COLOR = {color};\n"

        code += "\n"
        return code

    def _generate_data_prep(self) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Check if ADTTE exists ---*/
%macro check_adtte;
    %let dsid = %sysfunc(open(adam.adtte));
    %if &dsid > 0 %then %do;
        %let rc = %sysfunc(close(&dsid));
        %let ADTTE_EXISTS = 1;
        %put NOTE: ADTTE dataset found - proceeding with KM analysis;
    %end;
    %else %do;
        %let ADTTE_EXISTS = 0;
        %put WARNING: ADTTE dataset not found - creating from ADSL;
    %end;
%mend check_adtte;

%check_adtte;

%macro get_tte_data;
    %if &ADTTE_EXISTS = 1 %then %do;
        /*--- Use ADTTE ---*/
        data work.tte;
            set adam.adtte;
            where PARAMCD in ('OS', 'PFS', 'EFS', 'DFS', 'TTP', 'TTR')
                  and ANL01FL = 'Y';

            /* Convert time to appropriate units */
            %if %upcase(&TIME_UNIT) = MONTHS %then %do;
                AVAL_DISP = AVAL / 30.4375;  /* Days to months */
            %end;
            %else %if %upcase(&TIME_UNIT) = YEARS %then %do;
                AVAL_DISP = AVAL / 365.25;   /* Days to years */
            %end;
            %else %if %upcase(&TIME_UNIT) = WEEKS %then %do;
                AVAL_DISP = AVAL / 7;        /* Days to weeks */
            %end;
            %else %do;
                AVAL_DISP = AVAL;            /* Keep as days */
            %end;

            /* Event indicator (1=event, 0=censored) */
            if missing(CNSR) then CNSR = 0;
            EVENT = 1 - CNSR;
        run;
    %end;
    %else %do;
        /*--- Create basic TTE from ADSL (for studies without formal ADTTE) ---*/
        data work.tte;
            set adam.adsl;
            where ITTFL = 'Y';

            /* Calculate time on study */
            if not missing(TRTSDT) then do;
                if not missing(DTHDT) then do;
                    AVAL = DTHDT - TRTSDT + 1;
                    EVENT = 1;
                    CNSR = 0;
                end;
                else if not missing(LSTALVDT) then do;
                    AVAL = LSTALVDT - TRTSDT + 1;
                    EVENT = 0;
                    CNSR = 1;
                end;
                else if not missing(TRTEDT) then do;
                    AVAL = TRTEDT - TRTSDT + 1;
                    EVENT = 0;
                    CNSR = 1;
                end;
                else do;
                    AVAL = today() - TRTSDT + 1;
                    EVENT = 0;
                    CNSR = 1;
                end;
            end;

            /* Convert to display units */
            %if %upcase(&TIME_UNIT) = MONTHS %then %do;
                AVAL_DISP = AVAL / 30.4375;
            %end;
            %else %if %upcase(&TIME_UNIT) = YEARS %then %do;
                AVAL_DISP = AVAL / 365.25;
            %end;
            %else %if %upcase(&TIME_UNIT) = WEEKS %then %do;
                AVAL_DISP = AVAL / 7;
            %end;
            %else %do;
                AVAL_DISP = AVAL;
            %end;

            PARAMCD = 'OS';
            PARAM = 'Overall Survival';
        run;
    %end;

    /* Merge with ADSL for treatment info */
    proc sort data=work.tte; by USUBJID; run;
    proc sort data=adam.adsl out=work.adsl_trt (keep=USUBJID TRT01P TRT01PN ITTFL);
        by USUBJID;
    run;

    data work.km_data;
        merge work.tte (in=a)
              work.adsl_trt (in=b);
        by USUBJID;
        if a and b and ITTFL = 'Y';
    run;

    proc sort data=work.km_data;
        by TRT01PN;
    run;
%mend get_tte_data;

%get_tte_data;

"""

    def _generate_survival_analysis(self) -> str:
        """Generate survival analysis section."""
        return """/*============================================================================*/
/* Survival Analysis                                                          */
/*============================================================================*/

/*--- Kaplan-Meier estimates ---*/
ods output SurvivalPlot=work.km_plot
           ProductLimitEstimates=work.km_est
           Quartiles=work.km_quartiles
           HomTests=work.logrank;

proc lifetest data=work.km_data plots=survival(cl atrisk=0 to &TIME_MAX by &TIME_BY)
              timelist=(6 12 18 24) outsurv=work.km_surv;
    time AVAL_DISP * EVENT(0);
    strata TRT01P / test=logrank;
run;

ods output close;

/*--- Extract log-rank p-value ---*/
data work.logrank_p;
    set work.logrank;
    where Test = 'Log-Rank';
    keep ProbChiSq;
    rename ProbChiSq = LOGRANK_P;
run;

proc sql noprint;
    select LOGRANK_P format=pvalue6.4 into :LOGRANK_PVAL trimmed
    from work.logrank_p;
quit;

%put NOTE: Log-rank p-value = &LOGRANK_PVAL;

/*--- Calculate hazard ratio ---*/
proc phreg data=work.km_data;
    class TRT01PN (ref=last);
    model AVAL_DISP * EVENT(0) = TRT01PN;
    hazardratio TRT01PN / diff=ref;
    ods output HazardRatios=work.hr_results;
run;

/*--- Get HR and CI ---*/
data work.hr_display;
    set work.hr_results;
    length HR_DISP $50;
    HR_DISP = strip(put(HazardRatio, 5.2)) || ' (' ||
              strip(put(HRLowerCL, 5.2)) || ', ' ||
              strip(put(HRUpperCL, 5.2)) || ')';
run;

proc sql noprint;
    select HR_DISP into :HR_TEXT trimmed
    from work.hr_display;
quit;

%put NOTE: Hazard Ratio (95% CI) = &HR_TEXT;

/*--- Prepare at-risk numbers for each timepoint ---*/
%macro atrisk_numbers;
    %do t = 0 %to &TIME_MAX %by &TIME_BY;
        proc sql noprint;
            %do trt = 1 %to &N_TRTS;
                select count(*) into :N_ATRISK_&trt._&t trimmed
                from work.km_data
                where TRT01PN = &trt and AVAL_DISP >= &t;
            %end;
        quit;
    %end;
%mend atrisk_numbers;

%atrisk_numbers;

"""

    def _generate_km_plot_macro(self) -> str:
        """Generate the KM plot rendering macro."""
        return """/*============================================================================*/
/* Kaplan-Meier Plot Macro                                                    */
/*============================================================================*/

%macro km_plot_with_atrisk(data=, time_var=, event_var=, strata_var=,
                           time_max=, time_by=, outfile=);

    /* Template for KM plot with at-risk table */
    proc template;
        define statgraph kmplot_atrisk;
            begingraph / designwidth=&PLOT_WIDTH designheight=&PLOT_HEIGHT;

                entrytitle "Kaplan-Meier Curves for &ENDPOINT";
                entrytitle "ITT Population" / textattrs=(size=10pt);

                layout lattice / rows=2 rowweights=(0.85 0.15) columndatarange=union;

                    /* Main KM plot */
                    layout overlay /
                        xaxisopts=(label="Time (&TIME_UNIT)"
                                   linearopts=(viewmin=0 viewmax=&time_max
                                               tickvaluesequence=(start=0 end=&time_max increment=&time_by)))
                        yaxisopts=(label="Survival Probability"
                                   linearopts=(viewmin=0 viewmax=1.0
                                               tickvaluesequence=(start=0 end=1.0 increment=0.2)));

                        stepplot x=time y=survival / group=stratum name="km"
                                 lineattrs=(thickness=2);

                        /* Censoring marks */
                        scatterplot x=time y=survival / group=stratum
                                    markerattrs=(symbol=plus size=8);

                        /* Reference line at median */
                        referenceline y=0.5 / lineattrs=(pattern=dot color=gray);

                        discretelegend "km" / location=outside halign=right valign=top
                                              title="Treatment";

                        /* Add HR and p-value annotation */
                        entry halign=left valign=bottom
                              "HR (95% CI): &HR_TEXT"
                              / textattrs=(size=9pt);
                        entry halign=left valign=bottom
                              "Log-rank p = &LOGRANK_PVAL"
                              / textattrs=(size=9pt);

                    endlayout;

                    /* At-risk table */
                    layout overlay /
                        xaxisopts=(display=none
                                   linearopts=(viewmin=0 viewmax=&time_max))
                        yaxisopts=(display=none reverse=true);

                        blockplot x=tatrisk block=atrisk / class=stratum
                                  display=(values label)
                                  valuehalign=center
                                  labelposition=left
                                  labelattrs=(size=8pt weight=bold);

                    endlayout;

                endlayout;

            endgraph;
        end;
    run;

%mend km_plot_with_atrisk;

"""

    def _generate_plot_output(self, facts: Dict[str, Any], endpoint_name: str) -> str:
        """Generate plot output section."""
        return f"""/*============================================================================*/
/* Generate Kaplan-Meier Plot Output                                          */
/*============================================================================*/

options orientation=landscape nodate nonumber;
ods graphics on / reset=all width=&PLOT_WIDTH height=&PLOT_HEIGHT
                  imagefmt=png imagename="f_km";

/*--- Prepare survival data for plotting ---*/
data work.plot_data;
    set work.km_surv;
    where not missing(SURVIVAL);

    /* Ensure proper ordering */
    rename _CENSOR_ = CENSORED;
run;

/*--- Create at-risk dataset ---*/
data work.atrisk_data;
    length STRATUM $100 TATRISK 8 ATRISK $20;

    %do t = 0 %to &TIME_MAX %by &TIME_BY;
        %do trt = 1 %to &N_TRTS;
            STRATUM = "&&TRT&trt";
            TATRISK = &t;
            ATRISK = "&&N_ATRISK_&trt._&t";
            output;
        %end;
    %end;
run;

/*--- Generate KM plot using PROC LIFETEST ---*/
ods rtf file="&outpath./f_km.rtf" style=journal;

title1 "Figure &FIGURE_NUM";
title2 "&FIGURE_TITLE";
title3 "&ENDPOINT";
title4 "ITT Population";

footnote1 "Tick marks indicate censored observations";
footnote2 "HR = Hazard Ratio; CI = Confidence Interval";
footnote3 "Hazard Ratio (95% CI): &HR_TEXT    Log-rank p-value: &LOGRANK_PVAL";
footnote4 "Program: {self.program_name}  Output: f_km.rtf";

proc lifetest data=work.km_data
              plots=survival(cl test atrisk=0 to &TIME_MAX by &TIME_BY
                            nocensor strata=panel);
    time AVAL_DISP * EVENT(0);
    strata TRT01P / order=internal;
run;

ods rtf close;

title; footnote;

/*--- Also save as high-resolution PNG ---*/
ods listing gpath="&outpath.";
ods graphics on / reset=all width=10in height=7in imagefmt=png imagename="f_km_hires"
                  antialiasmax=10000;

proc lifetest data=work.km_data
              plots=survival(cl atrisk=0 to &TIME_MAX by &TIME_BY);
    time AVAL_DISP * EVENT(0);
    strata TRT01P / order=internal;
run;

ods listing close;
ods graphics off;

%put NOTE: Kaplan-Meier plot completed successfully;

"""

    def _generate_median_survival_table(self) -> str:
        """Generate median survival summary table."""
        return f"""/*============================================================================*/
/* Median Survival Summary Table                                              */
/*============================================================================*/

/*--- Format quartiles for display ---*/
data work.median_survival;
    set work.km_quartiles;
    where Percent = 50;

    length TRT_LABEL $100 MEDIAN_D $30 CI_D $50;

    TRT_LABEL = STRATUM;

    if not missing(Estimate) then
        MEDIAN_D = strip(put(Estimate, 8.1));
    else MEDIAN_D = 'NE';

    if not missing(LowerLimit) and not missing(UpperLimit) then
        CI_D = '(' || strip(put(LowerLimit, 8.1)) || ', ' ||
               strip(put(UpperLimit, 8.1)) || ')';
    else if not missing(LowerLimit) then
        CI_D = '(' || strip(put(LowerLimit, 8.1)) || ', NE)';
    else CI_D = '(NE, NE)';

    keep TRT_LABEL MEDIAN_D CI_D;
run;

/*--- Survival rates at landmark timepoints ---*/
proc sql;
    create table work.landmark_rates as
    select TRT01P,
           TIMELIST as TIMEPOINT,
           SURVIVAL * 100 as SURV_PCT format=5.1,
           SDF_LCL * 100 as LCL format=5.1,
           SDF_UCL * 100 as UCL format=5.1
    from work.km_est
    where TIMELIST in (6, 12, 18, 24)
    order by TRT01P, TIMEPOINT;
quit;

/*--- Generate survival summary table ---*/
ods rtf file="&outpath./t_survival.rtf" style=journal;

title1 "Table 14.2.3";
title2 "Summary of Survival Analysis";
title3 "ITT Population";

footnote1 "Median survival estimated using Kaplan-Meier method";
footnote2 "CI = Confidence Interval; NE = Not Estimable";
footnote3 "Program: {self.program_name}  Output: t_survival.rtf";

proc report data=work.median_survival nowd split='|';
    column TRT_LABEL MEDIAN_D CI_D;

    define TRT_LABEL / "Treatment" style(column)=[width=2in just=l];
    define MEDIAN_D / "Median (&TIME_UNIT)" style(column)=[width=1.5in just=c];
    define CI_D / "95% CI" style(column)=[width=1.5in just=c];
run;

ods rtf text="^S={{outputwidth=100% just=l}}";
ods rtf text="^S={{outputwidth=100% just=l}} Hazard Ratio (95% CI): &HR_TEXT";
ods rtf text="^S={{outputwidth=100% just=l}} Log-rank p-value: &LOGRANK_PVAL";

ods rtf close;

title; footnote;

/*--- Save analysis dataset ---*/
data adam.f_km_results;
    set work.km_surv;
run;

data adam.t_survival;
    set work.median_survival;
run;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program f_km.sas completed successfully;
%put NOTE: ================================================================;
"""
