#!/usr/bin/env python3
"""
Adverse Events Listing Generator
=================================

Generates SAS code for Listing 16.2.7: Adverse Events.
Provides subject-level adverse event data for safety population.

Output: l_ae.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class AdverseEventsListingGenerator(SASCodeGenerator):
    """Generate adverse events listing."""

    @property
    def program_name(self) -> str:
        return "l_ae.sas"

    @property
    def program_purpose(self) -> str:
        return "Listing 16.2.7: Adverse Events"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete AE listing program."""

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts)
        code += self._generate_data_prep()
        code += self._generate_listing_output(facts)
        code += self._generate_sae_listing()
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL', 'ADAE'],
            output_datasets=['l_ae.rtf', 'l_sae.rtf'],
            validation_notes=[
                "Verify all safety population subjects with AEs are included",
                "Check MedDRA coding is current version",
                "Confirm start/end dates are correct relative to treatment",
                "Validate severity grades match CRF data",
                "Cross-check SAE listing with separate SAE dataset if available"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any]) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

%let STUDYID = {study_id};
%let LISTING_NUM = 16.2.7;
%let LISTING_TITLE = Adverse Events;
%let outpath = /output/&STUDYID.;

/* MedDRA version - update as needed */
%let MEDDRA_VER = 26.0;

"""

    def _generate_data_prep(self) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Get safety population from ADSL ---*/
proc sort data=adam.adsl out=work.pop (keep=USUBJID SAFFL TRT01A TRT01AN TRTSDT);
    by USUBJID;
    where SAFFL = 'Y';
run;

/*--- Get AE data from ADAE ---*/
proc sort data=adam.adae out=work.ae;
    by USUBJID AESTDTC;
run;

/*--- Merge and prepare listing data ---*/
data work.ae_list;
    merge work.pop (in=a)
          work.ae (in=b);
    by USUBJID;
    if a and b;

    /* Create display variables */
    length SUBJID_D $20 TRT_D $100 AEDECOD_D $100 AEBODSYS_D $100
           AESTDT_D $12 AEENDT_D $12 AESEV_D $20 AESER_D $10
           AEREL_D $30 AEOUT_D $50 AEACN_D $50 DUR_D $20;

    /* Subject and treatment */
    SUBJID_D = USUBJID;
    TRT_D = TRT01A;

    /* AE terms */
    AEDECOD_D = propcase(AEDECOD);
    AEBODSYS_D = propcase(AEBODSYS);

    /* Dates */
    if not missing(AESTDT) then AESTDT_D = put(AESTDT, date9.);
    else if not missing(AESTDTC) then AESTDT_D = substr(AESTDTC, 1, 10);
    else AESTDT_D = 'Unknown';

    if not missing(AEENDT) then AEENDT_D = put(AEENDT, date9.);
    else if not missing(AEENDTC) then AEENDT_D = substr(AEENDTC, 1, 10);
    else if AEENRF = 'ONGOING' then AEENDT_D = 'Ongoing';
    else AEENDT_D = 'Unknown';

    /* Duration in days */
    if not missing(AESTDT) and not missing(AEENDT) then do;
        DUR_DAYS = AEENDT - AESTDT + 1;
        DUR_D = strip(put(DUR_DAYS, 8.)) || ' days';
    end;
    else if not missing(AEDUR) then DUR_D = strip(put(AEDUR, 8.)) || ' days';
    else DUR_D = 'NA';

    /* Severity */
    if not missing(AETOXGR) then AESEV_D = 'Grade ' || strip(AETOXGR);
    else if not missing(AESEV) then do;
        if upcase(AESEV) = 'MILD' then AESEV_D = 'Mild';
        else if upcase(AESEV) = 'MODERATE' then AESEV_D = 'Moderate';
        else if upcase(AESEV) = 'SEVERE' then AESEV_D = 'Severe';
        else AESEV_D = propcase(AESEV);
    end;
    else AESEV_D = 'NA';

    /* Serious */
    if AESER = 'Y' then AESER_D = 'Yes';
    else if AESER = 'N' then AESER_D = 'No';
    else AESER_D = 'NA';

    /* Relationship */
    if not missing(AEREL) then do;
        if upcase(AEREL) in ('RELATED', 'POSSIBLY RELATED', 'PROBABLY RELATED',
                             'DEFINITELY RELATED') then AEREL_D = 'Related';
        else if upcase(AEREL) in ('NOT RELATED', 'UNRELATED', 'UNLIKELY') then AEREL_D = 'Not Related';
        else AEREL_D = propcase(AEREL);
    end;
    else AEREL_D = 'NA';

    /* Outcome */
    if not missing(AEOUT) then do;
        select(upcase(AEOUT));
            when ('RECOVERED/RESOLVED') AEOUT_D = 'Resolved';
            when ('RECOVERING/RESOLVING') AEOUT_D = 'Resolving';
            when ('NOT RECOVERED/NOT RESOLVED') AEOUT_D = 'Not Resolved';
            when ('RECOVERED/RESOLVED WITH SEQUELAE') AEOUT_D = 'Resolved with Sequelae';
            when ('FATAL') AEOUT_D = 'Fatal';
            when ('UNKNOWN') AEOUT_D = 'Unknown';
            otherwise AEOUT_D = propcase(AEOUT);
        end;
    end;
    else AEOUT_D = 'NA';

    /* Action taken */
    if not missing(AEACN) then do;
        select(upcase(AEACN));
            when ('DRUG WITHDRAWN') AEACN_D = 'Withdrawn';
            when ('DOSE REDUCED') AEACN_D = 'Dose Reduced';
            when ('DOSE INCREASED') AEACN_D = 'Dose Increased';
            when ('DOSE NOT CHANGED') AEACN_D = 'No Change';
            when ('DRUG INTERRUPTED') AEACN_D = 'Interrupted';
            when ('NOT APPLICABLE') AEACN_D = 'N/A';
            otherwise AEACN_D = propcase(AEACN);
        end;
    end;
    else AEACN_D = 'NA';

    /* Study day of onset */
    if not missing(AESTDY) then ASTDY_D = put(AESTDY, 8.);
    else if not missing(AESTDT) and not missing(TRTSDT) then ASTDY_D = put(AESTDT - TRTSDT + 1, 8.);
    else ASTDY_D = 'NA';

    /* Flags for subsetting */
    SAE_FL = (AESER = 'Y');
    DRUG_REL_FL = (upcase(AEREL) in ('RELATED', 'POSSIBLY RELATED', 'PROBABLY RELATED',
                                      'DEFINITELY RELATED'));
run;

/*--- Sort for listing ---*/
proc sort data=work.ae_list;
    by TRT01AN USUBJID AESTDT AESEQ;
run;

"""

    def _generate_listing_output(self, facts: Dict[str, Any]) -> str:
        """Generate main AE listing output section."""
        return f"""/*============================================================================*/
/* Main AE Listing Output                                                     */
/*============================================================================*/

options orientation=landscape nodate nonumber;
ods escapechar='^';

ods rtf file="&outpath./l_ae.rtf" style=journal;

title1 "Listing &LISTING_NUM";
title2 "&LISTING_TITLE";
title3 "Safety Population";

footnote1 "MedDRA Version: &MEDDRA_VER";
footnote2 "Severity: Based on CTCAE grading when available, otherwise investigator assessment";
footnote3 "Relationship: Related includes possibly, probably, and definitely related";
footnote4 "Program: {self.program_name}  Output: l_ae.rtf";

proc report data=work.ae_list nowd split='|' spanrows;
    column TRT_D SUBJID_D AEBODSYS_D AEDECOD_D AESTDT_D AEENDT_D
           AESEV_D AESER_D AEREL_D AEOUT_D AEACN_D;

    define TRT_D / order "Treatment" style(column)=[width=1in just=l];
    define SUBJID_D / order "Subject|ID" style(column)=[width=0.9in just=l];
    define AEBODSYS_D / "System Organ|Class" style(column)=[width=1.2in just=l];
    define AEDECOD_D / "Preferred|Term" style(column)=[width=1.2in just=l];
    define AESTDT_D / "Start|Date" style(column)=[width=0.7in just=c];
    define AEENDT_D / "End|Date" style(column)=[width=0.7in just=c];
    define AESEV_D / "Severity" style(column)=[width=0.6in just=c];
    define AESER_D / "Serious" style(column)=[width=0.5in just=c];
    define AEREL_D / "Related" style(column)=[width=0.7in just=c];
    define AEOUT_D / "Outcome" style(column)=[width=0.8in just=l];
    define AEACN_D / "Action|Taken" style(column)=[width=0.7in just=l];

    break after TRT_D / page;
run;

ods rtf close;

title; footnote;

%put NOTE: Main AE listing completed;

"""

    def _generate_sae_listing(self) -> str:
        """Generate SAE-specific listing."""
        return f"""/*============================================================================*/
/* Serious Adverse Events Listing                                             */
/*============================================================================*/

/*--- Subset to SAEs only ---*/
data work.sae_list;
    set work.ae_list;
    where SAE_FL = 1;
run;

/*--- Check if any SAEs exist ---*/
proc sql noprint;
    select count(*) into :N_SAE from work.sae_list;
quit;

%macro generate_sae_listing;
    %if &N_SAE > 0 %then %do;

        ods rtf file="&outpath./l_sae.rtf" style=journal;

        title1 "Listing 16.2.7a";
        title2 "Serious Adverse Events";
        title3 "Safety Population";

        footnote1 "MedDRA Version: &MEDDRA_VER";
        footnote2 "Only subjects with at least one SAE are included";
        footnote3 "Program: {self.program_name}  Output: l_sae.rtf";

        proc report data=work.sae_list nowd split='|' spanrows;
            column TRT_D SUBJID_D AEBODSYS_D AEDECOD_D AESTDT_D AEENDT_D
                   AESEV_D AEREL_D AEOUT_D AEACN_D;

            define TRT_D / order "Treatment" style(column)=[width=1in just=l];
            define SUBJID_D / order "Subject|ID" style(column)=[width=0.9in just=l];
            define AEBODSYS_D / "System Organ|Class" style(column)=[width=1.3in just=l];
            define AEDECOD_D / "Preferred|Term" style(column)=[width=1.3in just=l];
            define AESTDT_D / "Start|Date" style(column)=[width=0.8in just=c];
            define AEENDT_D / "End|Date" style(column)=[width=0.8in just=c];
            define AESEV_D / "Severity" style(column)=[width=0.7in just=c];
            define AEREL_D / "Related" style(column)=[width=0.7in just=c];
            define AEOUT_D / "Outcome" style(column)=[width=0.9in just=l];
            define AEACN_D / "Action|Taken" style(column)=[width=0.8in just=l];

            break after TRT_D / page;
        run;

        ods rtf close;

        title; footnote;

        %put NOTE: SAE listing completed - &N_SAE SAEs found;

    %end;
    %else %do;
        %put NOTE: No SAEs found - SAE listing not generated;
    %end;
%mend generate_sae_listing;

%generate_sae_listing;

/*============================================================================*/
/* Drug-Related AE Listing                                                    */
/*============================================================================*/

/*--- Subset to drug-related AEs ---*/
data work.rel_ae_list;
    set work.ae_list;
    where DRUG_REL_FL = 1;
run;

proc sql noprint;
    select count(*) into :N_REL from work.rel_ae_list;
quit;

%macro generate_rel_ae_listing;
    %if &N_REL > 0 %then %do;

        ods rtf file="&outpath./l_ae_related.rtf" style=journal;

        title1 "Listing 16.2.7b";
        title2 "Drug-Related Adverse Events";
        title3 "Safety Population";

        footnote1 "MedDRA Version: &MEDDRA_VER";
        footnote2 "Includes AEs assessed as possibly, probably, or definitely related to study drug";
        footnote3 "Program: {self.program_name}  Output: l_ae_related.rtf";

        proc report data=work.rel_ae_list nowd split='|' spanrows;
            column TRT_D SUBJID_D AEBODSYS_D AEDECOD_D AESTDT_D AEENDT_D
                   AESEV_D AESER_D AEOUT_D AEACN_D;

            define TRT_D / order "Treatment" style(column)=[width=1in just=l];
            define SUBJID_D / order "Subject|ID" style(column)=[width=0.9in just=l];
            define AEBODSYS_D / "System Organ|Class" style(column)=[width=1.3in just=l];
            define AEDECOD_D / "Preferred|Term" style(column)=[width=1.3in just=l];
            define AESTDT_D / "Start|Date" style(column)=[width=0.8in just=c];
            define AEENDT_D / "End|Date" style(column)=[width=0.8in just=c];
            define AESEV_D / "Severity" style(column)=[width=0.7in just=c];
            define AESER_D / "Serious" style(column)=[width=0.5in just=c];
            define AEOUT_D / "Outcome" style(column)=[width=0.9in just=l];
            define AEACN_D / "Action|Taken" style(column)=[width=0.8in just=l];

            break after TRT_D / page;
        run;

        ods rtf close;

        title; footnote;

        %put NOTE: Drug-related AE listing completed - &N_REL related AEs found;

    %end;
    %else %do;
        %put NOTE: No drug-related AEs found - listing not generated;
    %end;
%mend generate_rel_ae_listing;

%generate_rel_ae_listing;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program l_ae.sas completed successfully;
%put NOTE: ================================================================;
"""
