#!/usr/bin/env python3
"""
Concomitant Medications Listing Generator
==========================================

Generates SAS code for Listing 16.2.4: Concomitant Medications.
Provides subject-level concomitant medication data for safety population.

Output: l_conmeds.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class ConcomitantMedsListingGenerator(SASCodeGenerator):
    """Generate concomitant medications listing."""

    @property
    def program_name(self) -> str:
        return "l_conmeds.sas"

    @property
    def program_purpose(self) -> str:
        return "Listing 16.2.4: Concomitant Medications"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete concomitant medications listing program."""

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts)
        code += self._generate_data_prep()
        code += self._generate_listing_output(facts)
        code += self._generate_prior_meds_listing()
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL', 'ADCM'],
            output_datasets=['l_conmeds.rtf', 'l_priormeds.rtf'],
            validation_notes=[
                "Verify WHO Drug Dictionary version is current",
                "Check medication start/end dates relative to treatment",
                "Confirm ATC classification is applied correctly",
                "Validate indication coding if applicable",
                "Cross-check with prohibited medications list"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any]) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

%let STUDYID = {study_id};
%let LISTING_NUM = 16.2.4;
%let LISTING_TITLE = Concomitant Medications;
%let outpath = /output/&STUDYID.;

/* WHO Drug Dictionary version - update as needed */
%let WHODRUG_VER = March 2024;

"""

    def _generate_data_prep(self) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Get safety population from ADSL ---*/
proc sort data=adam.adsl out=work.pop (keep=USUBJID SAFFL TRT01A TRT01AN TRTSDT TRTEDT);
    by USUBJID;
    where SAFFL = 'Y';
run;

/*--- Check if ADCM exists, otherwise use SDTM.CM ---*/
%macro get_cm_data;
    %let dsid = %sysfunc(open(adam.adcm));
    %if &dsid > 0 %then %do;
        %let rc = %sysfunc(close(&dsid));
        %put NOTE: Using ADAM.ADCM for concomitant medications;

        proc sort data=adam.adcm out=work.cm;
            by USUBJID CMSTDTC;
        run;
    %end;
    %else %do;
        %let dsid = %sysfunc(open(sdtm.cm));
        %if &dsid > 0 %then %do;
            %let rc = %sysfunc(close(&dsid));
            %put NOTE: Using SDTM.CM for concomitant medications;

            proc sort data=sdtm.cm out=work.cm;
                by USUBJID CMSTDTC;
            run;
        %end;
        %else %do;
            %put WARNING: No CM dataset found - creating empty dataset;
            data work.cm;
                length USUBJID $50 CMTRT $200 CMDECOD $200 CMSTDTC $20 CMENDTC $20
                       CMDOSE 8 CMDOSU $50 CMROUTE $50 CMINDC $200;
                stop;
            run;
        %end;
    %end;
%mend get_cm_data;

%get_cm_data;

/*--- Merge and prepare listing data ---*/
data work.cm_list;
    merge work.pop (in=a)
          work.cm (in=b);
    by USUBJID;
    if a and b;

    /* Create display variables */
    length SUBJID_D $20 TRT_D $100 CMTRT_D $100 CMDECOD_D $100
           CMSTDT_D $12 CMENDT_D $12 CMDOSE_D $30 CMROUTE_D $30
           CMINDC_D $100 CMCLAS_D $100 TIMING $20;

    /* Subject and treatment */
    SUBJID_D = USUBJID;
    TRT_D = TRT01A;

    /* Medication terms */
    if not missing(CMDECOD) then CMDECOD_D = propcase(CMDECOD);
    else CMDECOD_D = propcase(CMTRT);

    CMTRT_D = propcase(CMTRT);

    /* ATC classification if available */
    if not missing(CMCLAS) then CMCLAS_D = propcase(CMCLAS);
    else if not missing(CMCLASCD) then CMCLAS_D = CMCLASCD;
    else CMCLAS_D = 'Unclassified';

    /* Dates */
    if not missing(CMSTDT) then CMSTDT_D = put(CMSTDT, date9.);
    else if not missing(CMSTDTC) then CMSTDT_D = substr(CMSTDTC, 1, 10);
    else CMSTDT_D = 'Unknown';

    if not missing(CMENDT) then CMENDT_D = put(CMENDT, date9.);
    else if not missing(CMENDTC) then CMENDT_D = substr(CMENDTC, 1, 10);
    else if CMENRF = 'ONGOING' or missing(CMENDTC) then CMENDT_D = 'Ongoing';
    else CMENDT_D = 'Unknown';

    /* Dose and route */
    if not missing(CMDOSE) and not missing(CMDOSU) then
        CMDOSE_D = strip(put(CMDOSE, best12.)) || ' ' || strip(CMDOSU);
    else if not missing(CMDOSTXT) then CMDOSE_D = CMDOSTXT;
    else CMDOSE_D = 'NA';

    if not missing(CMROUTE) then CMROUTE_D = propcase(CMROUTE);
    else CMROUTE_D = 'NA';

    /* Indication */
    if not missing(CMINDC) then CMINDC_D = propcase(CMINDC);
    else CMINDC_D = 'NA';

    /* Timing relative to treatment */
    if not missing(CMSTDT) and not missing(TRTSDT) then do;
        if CMSTDT < TRTSDT then do;
            if not missing(CMENDT) and CMENDT >= TRTSDT then TIMING = 'Prior/Concomitant';
            else if missing(CMENDT) or CMENDT = 'Ongoing' then TIMING = 'Prior/Concomitant';
            else TIMING = 'Prior';
        end;
        else TIMING = 'Concomitant';
    end;
    else TIMING = 'Unknown';

    /* Flags for subsetting */
    PRIOR_FL = (TIMING in ('Prior', 'Prior/Concomitant'));
    CONCOM_FL = (TIMING in ('Concomitant', 'Prior/Concomitant'));
run;

/*--- Sort for listing ---*/
proc sort data=work.cm_list;
    by TRT01AN USUBJID CMCLAS_D CMSTDT_D;
run;

"""

    def _generate_listing_output(self, facts: Dict[str, Any]) -> str:
        """Generate main concomitant medications listing output section."""
        return f"""/*============================================================================*/
/* Concomitant Medications Listing Output                                     */
/*============================================================================*/

/*--- Subset to concomitant medications only ---*/
data work.concom_list;
    set work.cm_list;
    where CONCOM_FL = 1;
run;

proc sql noprint;
    select count(*) into :N_CONCOM from work.concom_list;
quit;

%macro generate_concom_listing;
    %if &N_CONCOM > 0 %then %do;

        options orientation=landscape nodate nonumber;
        ods escapechar='^';

        ods rtf file="&outpath./l_conmeds.rtf" style=journal;

        title1 "Listing &LISTING_NUM";
        title2 "&LISTING_TITLE";
        title3 "Safety Population";

        footnote1 "WHO Drug Dictionary Version: &WHODRUG_VER";
        footnote2 "Concomitant: Medications started on or after first dose of study drug";
        footnote3 "Prior/Concomitant: Medications started before but continued after first dose";
        footnote4 "Program: {self.program_name}  Output: l_conmeds.rtf";

        proc report data=work.concom_list nowd split='|' spanrows;
            column TRT_D SUBJID_D CMCLAS_D CMDECOD_D CMSTDT_D CMENDT_D
                   CMDOSE_D CMROUTE_D CMINDC_D;

            define TRT_D / order "Treatment" style(column)=[width=1in just=l];
            define SUBJID_D / order "Subject|ID" style(column)=[width=0.9in just=l];
            define CMCLAS_D / order "ATC Class" style(column)=[width=1.3in just=l];
            define CMDECOD_D / "Medication|Name" style(column)=[width=1.3in just=l];
            define CMSTDT_D / "Start|Date" style(column)=[width=0.8in just=c];
            define CMENDT_D / "End|Date" style(column)=[width=0.8in just=c];
            define CMDOSE_D / "Dose" style(column)=[width=0.8in just=c];
            define CMROUTE_D / "Route" style(column)=[width=0.6in just=c];
            define CMINDC_D / "Indication" style(column)=[width=1in just=l];

            break after TRT_D / page;
        run;

        ods rtf close;

        title; footnote;

        %put NOTE: Concomitant medications listing completed - &N_CONCOM records;

    %end;
    %else %do;
        %put NOTE: No concomitant medications found - listing not generated;
    %end;
%mend generate_concom_listing;

%generate_concom_listing;

"""

    def _generate_prior_meds_listing(self) -> str:
        """Generate prior medications listing."""
        return f"""/*============================================================================*/
/* Prior Medications Listing                                                  */
/*============================================================================*/

/*--- Subset to prior medications ---*/
data work.prior_list;
    set work.cm_list;
    where PRIOR_FL = 1;
run;

proc sql noprint;
    select count(*) into :N_PRIOR from work.prior_list;
quit;

%macro generate_prior_listing;
    %if &N_PRIOR > 0 %then %do;

        ods rtf file="&outpath./l_priormeds.rtf" style=journal;

        title1 "Listing 16.2.4a";
        title2 "Prior Medications";
        title3 "Safety Population";

        footnote1 "WHO Drug Dictionary Version: &WHODRUG_VER";
        footnote2 "Prior: Medications started and ended before first dose of study drug";
        footnote3 "Prior/Concomitant: Medications started before but continued after first dose";
        footnote4 "Program: {self.program_name}  Output: l_priormeds.rtf";

        proc report data=work.prior_list nowd split='|' spanrows;
            column TRT_D SUBJID_D CMCLAS_D CMDECOD_D CMSTDT_D CMENDT_D
                   CMDOSE_D CMROUTE_D CMINDC_D TIMING;

            define TRT_D / order "Treatment" style(column)=[width=1in just=l];
            define SUBJID_D / order "Subject|ID" style(column)=[width=0.8in just=l];
            define CMCLAS_D / order "ATC Class" style(column)=[width=1.2in just=l];
            define CMDECOD_D / "Medication|Name" style(column)=[width=1.2in just=l];
            define CMSTDT_D / "Start|Date" style(column)=[width=0.7in just=c];
            define CMENDT_D / "End|Date" style(column)=[width=0.7in just=c];
            define CMDOSE_D / "Dose" style(column)=[width=0.7in just=c];
            define CMROUTE_D / "Route" style(column)=[width=0.5in just=c];
            define CMINDC_D / "Indication" style(column)=[width=0.9in just=l];
            define TIMING / "Timing" style(column)=[width=0.8in just=c];

            break after TRT_D / page;
        run;

        ods rtf close;

        title; footnote;

        %put NOTE: Prior medications listing completed - &N_PRIOR records;

    %end;
    %else %do;
        %put NOTE: No prior medications found - listing not generated;
    %end;
%mend generate_prior_listing;

%generate_prior_listing;

/*============================================================================*/
/* Summary by ATC Class                                                       */
/*============================================================================*/

/*--- Create summary table of concomitant meds by ATC class ---*/
proc freq data=work.concom_list noprint;
    tables TRT_D * CMCLAS_D / out=work.cm_summary;
run;

ods rtf file="&outpath./l_conmeds_summary.rtf" style=journal;

title1 "Listing 16.2.4b";
title2 "Concomitant Medications Summary by ATC Class";
title3 "Safety Population";

footnote1 "Count represents number of medication records, not unique patients";
footnote2 "Program: {self.program_name}  Output: l_conmeds_summary.rtf";

proc report data=work.cm_summary nowd split='|';
    column TRT_D CMCLAS_D COUNT;

    define TRT_D / order "Treatment" style(column)=[width=1.5in just=l];
    define CMCLAS_D / "ATC Class" style(column)=[width=3in just=l];
    define COUNT / "N" style(column)=[width=1in just=c];

    break after TRT_D / page;
run;

ods rtf close;

title; footnote;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program l_conmeds.sas completed successfully;
%put NOTE: ================================================================;
"""
