#!/usr/bin/env python3
"""
Patient Demographics Listing Generator
=======================================

Generates SAS code for Listing 16.2.1: Patient Demographics.
Provides subject-level demographic data for all randomized patients.

Output: l_demog.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class DemographicsListingGenerator(SASCodeGenerator):
    """Generate patient demographics listing."""

    @property
    def program_name(self) -> str:
        return "l_demog.sas"

    @property
    def program_purpose(self) -> str:
        return "Listing 16.2.1: Patient Demographics"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete demographics listing program."""

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts)
        code += self._generate_data_prep()
        code += self._generate_listing_output(facts)
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL'],
            output_datasets=['l_demog.rtf'],
            validation_notes=[
                "Verify all randomized subjects are included",
                "Check subject identifiers are properly masked if required",
                "Confirm demographic variables match CRF specifications",
                "Validate age calculations"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any]) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)
        sponsor = self._get_fact(facts, 'sponsor', 'Sponsor')

        treatments = self._get_fact(facts, 'treatments', [])
        if not treatments:
            arm_names = self._get_fact(facts, 'arm_names', ['Treatment', 'Placebo'])
            treatments = [{'name': name} for name in arm_names]

        code = """/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

"""
        code += f"%let STUDYID = {study_id};\n"
        code += f"%let SPONSOR = {sponsor};\n"
        code += f"%let LISTING_NUM = 16.2.1;\n"
        code += f"%let LISTING_TITLE = Patient Demographics;\n\n"

        # Output path
        code += "%let outpath = /output/&STUDYID.;\n\n"

        return code

    def _generate_data_prep(self) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Get all randomized subjects from ADSL ---*/
data work.demog;
    set adam.adsl;
    where RANDFL = 'Y' or ITTFL = 'Y';

    /* Create display variables */
    length SUBJID_D $20 AGE_D $10 SEX_D $10 RACE_D $50 ETHNIC_D $50
           TRT_D $100 COUNTRY_D $20 SITE_D $20 RANDDT_D $12;

    /* Subject identifier - may need to mask per protocol */
    SUBJID_D = USUBJID;

    /* Age with units */
    if not missing(AGE) then AGE_D = strip(put(AGE, 8.)) || ' ' || strip(AGEU);
    else AGE_D = 'NA';

    /* Sex */
    if SEX = 'M' then SEX_D = 'Male';
    else if SEX = 'F' then SEX_D = 'Female';
    else SEX_D = strip(SEX);

    /* Race - handle multiple selections if needed */
    RACE_D = propcase(RACE);
    if length(RACE_D) > 50 then RACE_D = substr(RACE_D, 1, 47) || '...';

    /* Ethnicity */
    ETHNIC_D = propcase(ETHNIC);

    /* Treatment */
    TRT_D = TRT01P;

    /* Country and site */
    COUNTRY_D = COUNTRY;
    SITE_D = SITEID;

    /* Randomization date */
    if not missing(RANDDT) then RANDDT_D = put(RANDDT, date9.);
    else RANDDT_D = 'NA';

    /* Height and weight for BMI calculation display */
    length HEIGHT_D $15 WEIGHT_D $15 BMI_D $15;

    if not missing(HEIGHTBL) then HEIGHT_D = strip(put(HEIGHTBL, 8.1)) || ' cm';
    else HEIGHT_D = 'NA';

    if not missing(WEIGHTBL) then WEIGHT_D = strip(put(WEIGHTBL, 8.1)) || ' kg';
    else WEIGHT_D = 'NA';

    if not missing(BMIBL) then BMI_D = strip(put(BMIBL, 8.1)) || ' kg/m^2';
    else BMI_D = 'NA';
run;

/*--- Sort for listing ---*/
proc sort data=work.demog;
    by TRT01PN SITEID USUBJID;
run;

/*--- Add page break variables ---*/
data work.demog_final;
    set work.demog;
    by TRT01PN SITEID;

    /* Page break by treatment */
    if first.TRT01PN then PAGE_TRT = 1;
    else PAGE_TRT = 0;

    /* Row number within treatment */
    if first.TRT01PN then ROW_N = 0;
    ROW_N + 1;
run;

"""

    def _generate_listing_output(self, facts: Dict[str, Any]) -> str:
        """Generate listing output section."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')

        return f"""/*============================================================================*/
/* Listing Output                                                             */
/*============================================================================*/

options orientation=landscape nodate nonumber;
ods escapechar='^';

ods rtf file="&outpath./l_demog.rtf" style=journal;

title1 "Listing &LISTING_NUM";
title2 "&LISTING_TITLE";
title3 "All Randomized Subjects";

footnote1 "Note: All randomized subjects are included.";
footnote2 "BMI = Body Mass Index; NA = Not Available";
footnote3 "Program: {self.program_name}  Output: l_demog.rtf";

proc report data=work.demog_final nowd split='|' spanrows;
    column TRT_D SITE_D SUBJID_D AGE_D SEX_D RACE_D COUNTRY_D RANDDT_D;

    define TRT_D / order "Treatment" style(column)=[width=1.5in just=l];
    define SITE_D / order "Site" style(column)=[width=0.6in just=c];
    define SUBJID_D / "Subject|ID" style(column)=[width=1.2in just=l];
    define AGE_D / "Age" style(column)=[width=0.7in just=c];
    define SEX_D / "Sex" style(column)=[width=0.6in just=c];
    define RACE_D / "Race" style(column)=[width=1.5in just=l];
    define COUNTRY_D / "Country" style(column)=[width=0.7in just=c];
    define RANDDT_D / "Randomization|Date" style(column)=[width=1in just=c];

    break after TRT_D / page;
run;

ods rtf close;

title; footnote;

/*--- Generate extended listing with additional baseline characteristics ---*/
ods rtf file="&outpath./l_demog_extended.rtf" style=journal;

title1 "Listing &LISTING_NUM.a";
title2 "&LISTING_TITLE - Extended";
title3 "Baseline Characteristics - All Randomized Subjects";

footnote1 "Note: All randomized subjects are included.";
footnote2 "BMI = Body Mass Index (kg/m^2); NA = Not Available";
footnote3 "Program: {self.program_name}  Output: l_demog_extended.rtf";

proc report data=work.demog_final nowd split='|' spanrows;
    column TRT_D SUBJID_D AGE_D SEX_D HEIGHT_D WEIGHT_D BMI_D;

    define TRT_D / order "Treatment" style(column)=[width=1.5in just=l];
    define SUBJID_D / "Subject|ID" style(column)=[width=1.2in just=l];
    define AGE_D / "Age" style(column)=[width=0.8in just=c];
    define SEX_D / "Sex" style(column)=[width=0.6in just=c];
    define HEIGHT_D / "Height" style(column)=[width=0.9in just=c];
    define WEIGHT_D / "Weight" style(column)=[width=0.9in just=c];
    define BMI_D / "BMI" style(column)=[width=1in just=c];

    break after TRT_D / page;
run;

ods rtf close;

title; footnote;

%put NOTE: Demographics listing completed successfully;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program l_demog.sas completed successfully;
%put NOTE: ================================================================;
"""
