#!/usr/bin/env python3
"""
Patient Disposition Table Generator
=====================================

Generates SAS code for Table 14.1.2: Patient Disposition.
Shows patient flow through the study including randomization,
treatment, completion, and discontinuation reasons.

Output: t_disp.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class DispositionTableGenerator(SASCodeGenerator):
    """Generate patient disposition table."""

    @property
    def program_name(self) -> str:
        return "t_disp.sas"

    @property
    def program_purpose(self) -> str:
        return "Table 14.1.2: Patient Disposition"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete disposition table program."""

        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts)
        code += self._generate_data_prep()
        code += self._generate_analysis_section(facts)
        code += self._generate_report_section(facts)
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL'],
            output_datasets=['t_disp.rtf', 't_disp.sas7bdat'],
            validation_notes=[
                "Verify screened count matches enrollment log",
                "Check randomized count matches IXRS/IVRS data",
                "Confirm discontinuation reasons align with CRF categories",
                "Validate completion definition per protocol"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any]) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        treatments = self._get_fact(facts, 'treatments', [])
        if not treatments:
            arm_names = self._get_fact(facts, 'arm_names', ['Treatment', 'Placebo'])
            treatments = [{'name': name} for name in arm_names]

        code = f"""/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

%let STUDYID = {study_id};
%let TABLE_NUM = 14.1.2;
%let TABLE_TITLE = Patient Disposition;
%let outpath = /output/&STUDYID.;

/* Treatment arms */
%let N_TRTS = {len(treatments)};
"""
        for i, trt in enumerate(treatments, 1):
            name = trt.get('name', f'Treatment {i}')
            code += f"%let TRT{i} = {name};\n"

        code += "\n"
        return code

    def _generate_data_prep(self) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Get disposition data from ADSL ---*/
data work.disp;
    set adam.adsl;

    /* Ensure key flags exist */
    if missing(RANDFL) then RANDFL = 'N';
    if missing(SAFFL) then SAFFL = 'N';
    if missing(ITTFL) then ITTFL = 'N';
    if missing(COMPLFL) then COMPLFL = 'N';

    /* Create numeric treatment for ordering */
    if missing(TRT01PN) then TRT01PN = 99;

    /* Standardize discontinuation reason */
    length DCSREAS_STD $50;
    if not missing(DCSREAS) then do;
        DCSREAS_UP = upcase(DCSREAS);
        select;
            when (index(DCSREAS_UP, 'ADVERSE') > 0) DCSREAS_STD = 'Adverse Event';
            when (index(DCSREAS_UP, 'WITHDRAW') > 0 or
                  index(DCSREAS_UP, 'CONSENT') > 0) DCSREAS_STD = 'Withdrawal by Subject';
            when (index(DCSREAS_UP, 'EFFICACY') > 0 or
                  index(DCSREAS_UP, 'LACK') > 0) DCSREAS_STD = 'Lack of Efficacy';
            when (index(DCSREAS_UP, 'PROTOCOL') > 0 or
                  index(DCSREAS_UP, 'DEVIATION') > 0) DCSREAS_STD = 'Protocol Deviation';
            when (index(DCSREAS_UP, 'LOST') > 0 or
                  index(DCSREAS_UP, 'FOLLOW') > 0) DCSREAS_STD = 'Lost to Follow-up';
            when (index(DCSREAS_UP, 'DEATH') > 0 or
                  index(DCSREAS_UP, 'DIED') > 0) DCSREAS_STD = 'Death';
            when (index(DCSREAS_UP, 'PHYSICIAN') > 0 or
                  index(DCSREAS_UP, 'INVESTIGATOR') > 0) DCSREAS_STD = 'Physician Decision';
            when (index(DCSREAS_UP, 'SPONSOR') > 0) DCSREAS_STD = 'Sponsor Decision';
            when (index(DCSREAS_UP, 'OTHER') > 0) DCSREAS_STD = 'Other';
            otherwise DCSREAS_STD = propcase(DCSREAS);
        end;
    end;
    else if COMPLFL = 'N' then DCSREAS_STD = 'Unknown';
run;

/*--- Get screening data if available ---*/
%macro get_screened;
    %let dsid = %sysfunc(open(sdtm.dm));
    %if &dsid > 0 %then %do;
        %let rc = %sysfunc(close(&dsid));

        proc sql noprint;
            select count(distinct USUBJID) into :N_SCREENED trimmed
            from sdtm.dm;
        quit;

        /* Screen failures */
        proc sql noprint;
            select count(distinct a.USUBJID) into :N_SCRFAIL trimmed
            from sdtm.dm a
            left join adam.adsl b on a.USUBJID = b.USUBJID
            where b.USUBJID is null or b.RANDFL ne 'Y';
        quit;
    %end;
    %else %do;
        /* Use ADSL only */
        proc sql noprint;
            select count(distinct USUBJID) into :N_SCREENED trimmed
            from adam.adsl;
        quit;
        %let N_SCRFAIL = 0;
    %end;
%mend get_screened;

%get_screened;

"""

    def _generate_analysis_section(self, facts: Dict[str, Any]) -> str:
        """Generate statistical analysis section."""
        treatments = self._get_fact(facts, 'treatments', [])
        n_trts = len(treatments) if treatments else 2

        return f"""/*============================================================================*/
/* Analysis Section                                                           */
/*============================================================================*/

/*--- Calculate disposition counts by treatment ---*/
proc sql;
    create table work.disp_counts as
    select TRT01PN,
           TRT01P,
           count(distinct USUBJID) as N_RAND,
           sum(SAFFL = 'Y') as N_SAFETY,
           sum(ITTFL = 'Y') as N_ITT,
           sum(COMPLFL = 'Y') as N_COMPL,
           sum(COMPLFL = 'N') as N_DISC
    from work.disp
    where RANDFL = 'Y'
    group by TRT01PN, TRT01P;
quit;

/*--- Calculate total column ---*/
proc sql;
    create table work.disp_total as
    select 99 as TRT01PN,
           'Total' as TRT01P,
           count(distinct USUBJID) as N_RAND,
           sum(SAFFL = 'Y') as N_SAFETY,
           sum(ITTFL = 'Y') as N_ITT,
           sum(COMPLFL = 'Y') as N_COMPL,
           sum(COMPLFL = 'N') as N_DISC
    from work.disp
    where RANDFL = 'Y';
quit;

/*--- Combine treatment and total ---*/
data work.disp_all;
    set work.disp_counts
        work.disp_total;
run;

/*--- Discontinuation reasons by treatment ---*/
proc sql;
    create table work.dc_reasons as
    select TRT01PN,
           TRT01P,
           DCSREAS_STD,
           count(distinct USUBJID) as N_DC
    from work.disp
    where RANDFL = 'Y' and COMPLFL = 'N' and not missing(DCSREAS_STD)
    group by TRT01PN, TRT01P, DCSREAS_STD;
quit;

/*--- Discontinuation reasons for total ---*/
proc sql;
    create table work.dc_reasons_total as
    select 99 as TRT01PN,
           'Total' as TRT01P,
           DCSREAS_STD,
           count(distinct USUBJID) as N_DC
    from work.disp
    where RANDFL = 'Y' and COMPLFL = 'N' and not missing(DCSREAS_STD)
    group by DCSREAS_STD;
quit;

data work.dc_all;
    set work.dc_reasons
        work.dc_reasons_total;
run;

/*--- Build final disposition table dataset ---*/
data work.disp_final;
    length ROW_LABEL $100 COL1-COL{n_trts + 1} $50 ROW_ORDER 8;

    /* Row 1: Screened */
    ROW_ORDER = 1;
    ROW_LABEL = 'Patients screened';
    COL1 = strip(put(&N_SCREENED, comma8.));
    %do i = 2 %to {n_trts + 1};
        COL&i = '';
    %end;
    output;

    /* Row 2: Screen failures */
    ROW_ORDER = 2;
    ROW_LABEL = '  Screen failures';
    COL1 = strip(put(&N_SCRFAIL, comma8.));
    %do i = 2 %to {n_trts + 1};
        COL&i = '';
    %end;
    output;
run;

/*--- Add randomized and population rows ---*/
data work.disp_rows;
    set work.disp_all;
    length ROW_LABEL $100 STAT $50;

    /* Randomized */
    ROW_ORDER = 3;
    ROW_LABEL = 'Patients randomized';
    STAT = strip(put(N_RAND, comma8.));
    output;

    /* Safety population */
    ROW_ORDER = 4;
    ROW_LABEL = '  Safety population';
    STAT = strip(put(N_SAFETY, comma8.)) || ' (' ||
           strip(put(N_SAFETY/N_RAND*100, 5.1)) || '%)';
    output;

    /* ITT population */
    ROW_ORDER = 5;
    ROW_LABEL = '  ITT population';
    STAT = strip(put(N_ITT, comma8.)) || ' (' ||
           strip(put(N_ITT/N_RAND*100, 5.1)) || '%)';
    output;

    /* Completed */
    ROW_ORDER = 6;
    ROW_LABEL = 'Completed study';
    STAT = strip(put(N_COMPL, comma8.)) || ' (' ||
           strip(put(N_COMPL/N_RAND*100, 5.1)) || '%)';
    output;

    /* Discontinued */
    ROW_ORDER = 7;
    ROW_LABEL = 'Discontinued study';
    STAT = strip(put(N_DISC, comma8.)) || ' (' ||
           strip(put(N_DISC/N_RAND*100, 5.1)) || '%)';
    output;

    keep TRT01PN ROW_ORDER ROW_LABEL STAT;
run;

/*--- Transpose to wide format ---*/
proc sort data=work.disp_rows; by ROW_ORDER ROW_LABEL; run;

proc transpose data=work.disp_rows out=work.disp_wide prefix=COL;
    by ROW_ORDER ROW_LABEL;
    id TRT01PN;
    var STAT;
run;

/*--- Add discontinuation reason rows ---*/
data work.dc_rows;
    set work.dc_all;
    length ROW_LABEL $100 STAT $50;

    /* Get N for percentage calculation */
    set work.disp_all (keep=TRT01PN N_RAND rename=(N_RAND=N_DENOM)) key=TRT01PN;

    ROW_ORDER = 8;
    ROW_LABEL = '  ' || strip(DCSREAS_STD);
    STAT = strip(put(N_DC, comma8.)) || ' (' ||
           strip(put(N_DC/N_DENOM*100, 5.1)) || '%)';

    keep TRT01PN ROW_ORDER ROW_LABEL STAT DCSREAS_STD;
run;

proc sort data=work.dc_rows; by DCSREAS_STD ROW_LABEL; run;

proc transpose data=work.dc_rows out=work.dc_wide prefix=COL;
    by ROW_ORDER ROW_LABEL;
    id TRT01PN;
    var STAT;
run;

/*--- Combine all rows ---*/
data work.report_data;
    set work.disp_final
        work.disp_wide
        work.dc_wide;
    by ROW_ORDER;

    /* Clean up column names */
    array cols COL:;
    do over cols;
        if missing(cols) then cols = '';
    end;
run;

proc sort data=work.report_data; by ROW_ORDER ROW_LABEL; run;

"""

    def _generate_report_section(self, facts: Dict[str, Any]) -> str:
        """Generate report output section."""
        treatments = self._get_fact(facts, 'treatments', [])
        n_trts = len(treatments) if treatments else 2

        col_defs = ""
        for i in range(1, n_trts + 2):
            if i <= n_trts:
                col_defs += f"    define COL{i} / \"&&TRT{i}\" style(column)=[width=1.2in just=c];\n"
            else:
                col_defs += f"    define COL{i} / \"Total\" style(column)=[width=1.2in just=c];\n"

        return f"""/*============================================================================*/
/* Report Generation                                                          */
/*============================================================================*/

options orientation=portrait nodate nonumber;
ods escapechar='^';

ods rtf file="&outpath./t_disp.rtf" style=journal;

title1 "Table &TABLE_NUM";
title2 "&TABLE_TITLE";

footnote1 "Percentages are based on number of randomized patients in each treatment group.";
footnote2 "Program: {self.program_name}  Output: t_disp.rtf";

proc report data=work.report_data nowd split='|';
    column ROW_ORDER ROW_LABEL COL1-COL{n_trts + 1};

    define ROW_ORDER / order noprint;
    define ROW_LABEL / " " style(column)=[width=2.5in just=l];
{col_defs}
run;

ods rtf close;

title; footnote;

/*--- Save analysis dataset ---*/
data adam.t_disp;
    set work.report_data;
run;

%put NOTE: Disposition table completed successfully;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program t_disp.sas completed successfully;
%put NOTE: ================================================================;
"""
