#!/usr/bin/env python3
"""
Secondary Efficacy Table Generator
===================================

Generates SAS code for Table 14.2.x: Secondary Efficacy Endpoints.
Handles multiple secondary endpoints with appropriate statistical methods.

Output: t_secondary.sas
"""

from typing import Dict, Any, List
from ..base import SASCodeGenerator, CodeGenerationResult


class SecondaryEfficacyTableGenerator(SASCodeGenerator):
    """Generate secondary efficacy analysis table."""

    @property
    def program_name(self) -> str:
        return "t_secondary.sas"

    @property
    def program_purpose(self) -> str:
        return "Table 14.2.2: Secondary Efficacy Endpoints Analysis"

    def _get_fact(self, facts: Any, key: str, default: Any = None) -> Any:
        """Get a fact from either dict or object."""
        if isinstance(facts, dict):
            return facts.get(key, default)
        return getattr(facts, key, default)

    def generate(self, facts: Dict[str, Any]) -> CodeGenerationResult:
        """Generate complete secondary efficacy table program."""

        # Extract protocol information
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)
        drug_name = self._get_fact(facts, 'drug_name', 'Study Drug')
        therapeutic_area = self._get_fact(facts, 'therapeutic_area', 'general')

        # Get endpoints
        secondary_endpoints = self._get_fact(facts, 'secondary_endpoints', [])
        primary_timepoint = self._get_fact(facts, 'primary_timepoint', {})
        if isinstance(primary_timepoint, dict):
            timepoint = primary_timepoint.get('visit', 'Week 12')
        else:
            timepoint = str(primary_timepoint) if primary_timepoint else 'Week 12'

        # Get treatment info
        treatments = self._get_fact(facts, 'treatments', [])
        if not treatments:
            arm_names = self._get_fact(facts, 'arm_names', ['Treatment', 'Placebo'])
            treatments = [{'name': name, 'code': f'TRT{i+1}'} for i, name in enumerate(arm_names)]

        # Build the SAS code
        code = self._generate_header(facts)
        code += self._generate_macro_variables(facts, treatments, secondary_endpoints)
        code += self._generate_data_prep(therapeutic_area)
        code += self._generate_analysis_section(secondary_endpoints, therapeutic_area)
        code += self._generate_report_section(secondary_endpoints, treatments)
        code += self._generate_footer()

        return CodeGenerationResult(
            program_name=self.program_name,
            code=code,
            description=self.program_purpose,
            input_datasets=['ADSL', 'ADEFF'],
            output_datasets=['t_secondary.rtf', 't_secondary.sas7bdat'],
            validation_notes=[
                "Verify all secondary endpoints are included",
                "Check statistical methods match SAP specifications",
                "Confirm multiplicity adjustment if applicable",
                "Validate responder definitions for each endpoint"
            ]
        )

    def _generate_header(self, facts: Dict[str, Any]) -> str:
        """Generate program header."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        return f"""/*============================================================================*/
/* Program: {self.program_name}                                               */
/* Study: {study_id}                                                          */
/* Purpose: {self.program_purpose}                                            */
/*----------------------------------------------------------------------------*/
/* Created: {self._get_date()}                                                */
/* Author: Auto-generated by SAP System                                       */
/*----------------------------------------------------------------------------*/
/* Modification History:                                                      */
/* Date       Author      Description                                         */
/* {self._get_date()}  SYSTEM      Initial version                            */
/*============================================================================*/

"""

    def _get_date(self) -> str:
        """Get current date in SAS format."""
        from datetime import datetime
        return datetime.now().strftime("%d%b%Y").upper()

    def _generate_macro_variables(self, facts: Dict[str, Any], treatments: List[Dict],
                                   endpoints: List) -> str:
        """Generate macro variable definitions."""
        protocol_id = self._get_fact(facts, 'protocol_id', 'UNKNOWN')
        study_id = self._get_fact(facts, 'study_id', protocol_id)

        primary_timepoint = self._get_fact(facts, 'primary_timepoint', {})
        if isinstance(primary_timepoint, dict):
            timepoint = primary_timepoint.get('visit', 'Week 12')
        else:
            timepoint = str(primary_timepoint) if primary_timepoint else 'Week 12'

        code = """/*============================================================================*/
/* Macro Variables                                                            */
/*============================================================================*/

"""
        code += f"%let STUDYID = {study_id};\n"
        code += f"%let TIMEPOINT = {timepoint};\n"
        code += f"%let N_ENDPOINTS = {len(endpoints)};\n\n"

        # Treatment arms
        for i, trt in enumerate(treatments, 1):
            name = trt.get('name', f'Treatment {i}')
            code += f"%let TRT{i} = {name};\n"

        code += f"\n%let N_TRTS = {len(treatments)};\n"

        # Secondary endpoints
        code += "\n/* Secondary Endpoints */\n"
        for i, ep in enumerate(endpoints, 1):
            if isinstance(ep, dict):
                ep_name = ep.get('name', f'Endpoint {i}')
                ep_param = ep.get('parameter', f'SEC{i}')
            else:
                ep_name = str(ep)
                ep_param = f'SEC{i}'
            code += f"%let EP{i}_NAME = {ep_name};\n"
            code += f"%let EP{i}_PARAM = {ep_param};\n"

        code += "\n"
        return code

    def _generate_data_prep(self, therapeutic_area: str) -> str:
        """Generate data preparation section."""
        return """/*============================================================================*/
/* Data Preparation                                                           */
/*============================================================================*/

/*--- Get analysis population from ADSL ---*/
proc sort data=adam.adsl out=work.pop (keep=USUBJID ITTFL SAFFL TRT01P TRT01PN);
    by USUBJID;
    where ITTFL = 'Y';
run;

/*--- Get efficacy data from ADEFF ---*/
proc sort data=adam.adeff out=work.eff;
    by USUBJID PARAMCD AVISIT;
    where ANL01FL = 'Y';
run;

/*--- Merge population with efficacy ---*/
data work.analysis;
    merge work.pop (in=a)
          work.eff (in=b);
    by USUBJID;
    if a and b;

    /* Create numeric response variable */
    if AVALC = 'Y' then RESP = 1;
    else if AVALC = 'N' then RESP = 0;
    else RESP = .;
run;

/*--- Get endpoint list ---*/
proc sql noprint;
    select distinct PARAMCD, PARAM
    into :EP_LIST separated by '|',
         :EP_NAMES separated by '|'
    from work.analysis
    where PARAMCD not in ('PRMEFF')  /* Exclude primary endpoint */
    order by PARAMCD;

    %let N_SEC_EP = &sqlobs;
quit;

%put NOTE: Found &N_SEC_EP secondary endpoints;

"""

    def _generate_analysis_section(self, endpoints: List, therapeutic_area: str) -> str:
        """Generate statistical analysis section."""
        return """/*============================================================================*/
/* Statistical Analysis                                                       */
/*============================================================================*/

/*--- Macro for binary endpoint analysis ---*/
%macro analyze_binary(paramcd=, param=, outds=);

    /* Get data for this endpoint */
    data work._ep_data;
        set work.analysis;
        where PARAMCD = "&paramcd";
    run;

    /* Calculate response rates by treatment */
    proc freq data=work._ep_data noprint;
        tables TRT01PN * RESP / outpct out=work._freq;
        where not missing(RESP);
    run;

    /* Get responders and totals */
    proc sql noprint;
        create table work._stats as
        select TRT01PN,
               TRT01P,
               sum(case when RESP=1 then 1 else 0 end) as N_RESP,
               count(*) as N_TOTAL,
               calculated N_RESP / calculated N_TOTAL * 100 as PCT_RESP
        from work._ep_data
        where not missing(RESP)
        group by TRT01PN, TRT01P;
    quit;

    /* CMH test stratified if applicable */
    proc freq data=work._ep_data;
        tables TRT01PN * RESP / cmh noprint;
        where not missing(RESP);
        output out=work._cmh cmh;
    run;

    /* Fisher's exact test for small samples */
    proc freq data=work._ep_data;
        tables TRT01PN * RESP / fisher exact noprint;
        where not missing(RESP);
        output out=work._fisher fisher;
    run;

    /* Combine results */
    data work.&outds;
        length PARAMCD $8 PARAM $200 STATISTIC $50 TRT01P $200;
        set work._stats;
        PARAMCD = "&paramcd";
        PARAM = "&param";

        /* Format statistics */
        STAT_N = strip(put(N_RESP, 8.)) || '/' || strip(put(N_TOTAL, 8.));
        STAT_PCT = strip(put(PCT_RESP, 5.1)) || '%';
        STAT_DISPLAY = strip(STAT_N) || ' (' || strip(STAT_PCT) || ')';
    run;

    /* Clean up */
    proc datasets library=work nolist;
        delete _ep_data _freq _stats _cmh _fisher;
    quit;

%mend analyze_binary;

/*--- Macro for continuous endpoint analysis ---*/
%macro analyze_continuous(paramcd=, param=, outds=);

    /* Get data for this endpoint */
    data work._ep_data;
        set work.analysis;
        where PARAMCD = "&paramcd";
    run;

    /* Descriptive statistics by treatment */
    proc means data=work._ep_data noprint;
        class TRT01PN TRT01P;
        var AVAL CHG;
        output out=work._stats
            n=N_AVAL N_CHG
            mean=MEAN_AVAL MEAN_CHG
            std=SD_AVAL SD_CHG
            median=MED_AVAL MED_CHG
            min=MIN_AVAL MIN_CHG
            max=MAX_AVAL MAX_CHG;
    run;

    /* ANCOVA for change from baseline */
    proc mixed data=work._ep_data;
        class TRT01PN;
        model CHG = TRT01PN BASE / solution ddfm=kr;
        lsmeans TRT01PN / diff cl;
        ods output LSMeans=work._lsmeans Diffs=work._diffs;
    run;

    /* Combine results */
    data work.&outds;
        length PARAMCD $8 PARAM $200;
        merge work._stats (where=(_TYPE_=3))
              work._lsmeans;
        by TRT01PN;
        PARAMCD = "&paramcd";
        PARAM = "&param";

        /* Format for display */
        STAT_N = strip(put(N_CHG, 8.));
        STAT_MEAN = strip(put(MEAN_CHG, 8.2));
        STAT_SD = strip(put(SD_CHG, 8.2));
        STAT_LSM = strip(put(Estimate, 8.2));
        STAT_CI = '(' || strip(put(Lower, 8.2)) || ', ' || strip(put(Upper, 8.2)) || ')';
    run;

    /* Clean up */
    proc datasets library=work nolist;
        delete _ep_data _stats _lsmeans _diffs;
    quit;

%mend analyze_continuous;

/*--- Analyze each secondary endpoint ---*/
%macro analyze_all_endpoints;

    /* Get unique endpoints */
    proc sql noprint;
        select distinct PARAMCD, PARAM, DTYPE
        into :PLIST1-:PLIST99,
             :NLIST1-:NLIST99,
             :TLIST1-:TLIST99
        from work.analysis
        where PARAMCD not in ('PRMEFF');

        %let N_EP = &sqlobs;
    quit;

    %do i = 1 %to &N_EP;
        %let _paramcd = &&PLIST&i;
        %let _param = &&NLIST&i;
        %let _type = &&TLIST&i;

        %put NOTE: Analyzing endpoint &i: &_paramcd - &_param;

        /* Determine endpoint type and analyze */
        %if %upcase(&_type) = BINARY or %index(%upcase(&_param), RESPONSE) > 0
            or %index(%upcase(&_param), REMISSION) > 0 %then %do;
            %analyze_binary(paramcd=&_paramcd, param=&_param, outds=_result&i);
        %end;
        %else %do;
            %analyze_continuous(paramcd=&_paramcd, param=&_param, outds=_result&i);
        %end;
    %end;

    /* Stack all results */
    data work.all_results;
        set %do i = 1 %to &N_EP; work._result&i %end;;
    run;

%mend analyze_all_endpoints;

%analyze_all_endpoints;

"""

    def _generate_report_section(self, endpoints: List, treatments: List[Dict]) -> str:
        """Generate report output section."""
        n_trts = len(treatments)

        return f"""/*============================================================================*/
/* Report Generation                                                          */
/*============================================================================*/

/*--- Prepare final report dataset ---*/
proc sort data=work.all_results;
    by PARAMCD TRT01PN;
run;

proc transpose data=work.all_results out=work.report_wide prefix=TRT;
    by PARAMCD PARAM;
    id TRT01PN;
    var STAT_DISPLAY;
run;

/*--- Create comparison columns ---*/
data work.report_final;
    set work.report_wide;

    /* Add row labels */
    length ROW_LABEL $200;
    ROW_LABEL = PARAM;

    /* Endpoint order */
    EPORD = _N_;
run;

/*--- Generate RTF output ---*/
options orientation=landscape nodate nonumber;
ods escapechar='^';

ods rtf file="&outpath./t_secondary.rtf" style=journal;

title1 "Table 14.2.2";
title2 "Secondary Efficacy Endpoints Analysis";
title3 "ITT Population";

footnote1 "^{{super a}} n/N (%): Number of responders / Total analyzed (percentage)";
footnote2 "^{{super b}} p-value from Cochran-Mantel-Haenszel test for binary endpoints";
footnote3 "^{{super c}} p-value from ANCOVA with baseline as covariate for continuous endpoints";
footnote4 "Program: {self.program_name}  Output: t_secondary.rtf";

proc report data=work.report_final nowd split='|';
    column EPORD ROW_LABEL ("Treatment Groups" TRT1-TRT{n_trts});

    define EPORD / order noprint;
    define ROW_LABEL / "Endpoint" style(column)=[width=3in just=l];

    %do i = 1 %to &N_TRTS;
        define TRT&i / "&&TRT&i" style(column)=[width=1.5in just=c];
    %end;

    compute after ROW_LABEL;
        line ' ';
    endcomp;
run;

ods rtf close;

title; footnote;

/*--- Save analysis dataset ---*/
data adam.t_secondary;
    set work.report_final;
run;

%put NOTE: Secondary efficacy table completed successfully;

"""

    def _generate_footer(self) -> str:
        """Generate program footer."""
        return """/*============================================================================*/
/* Program Completion                                                         */
/*============================================================================*/

proc datasets library=work kill nolist;
quit;

%put NOTE: ================================================================;
%put NOTE: Program t_secondary.sas completed successfully;
%put NOTE: ================================================================;
"""
